name: setup gen-ssp
description: Setup Santa Service Protocol generate utils
runs:
  using: composite
  steps:
    - uses: denoland/setup-deno@v1
      with:
        deno-version: v1.19.0
    - uses: actions/checkout@v2
      with:
        repository: riiid/toolbelt
        ref: main
        path: tmp/toolbelt
        clean: false
        fetch-depth: 1
    - run: |-
        deno install -A --unstable \
          -n gen-ssp \
          tmp/toolbelt/gen-ssp/gen/index.ts
      shell: bash
